# Dependencies
highlighter:      rouge

# Permalinks
permalink:        /:categories/:title/

# Setup
title:            Hyperparticle
tagline:          'Recursion is Recursive'
description:      'Elements of Programming and Mathematics'
url:              https://hyperparticle.com

author:
  name:           'Dan Kondratyuk'
  url:            https://hyperparticle.com

paginate:         5

# Default vars
defaults:
  # Post comments
  - scope:
      path: '' # All files in the project
      type: 'posts'
    values:
      comments: true
  # Author info
  - scope:
      path: ''
    values:
      author: 'Dan Kondratyuk'
      avatar: '/public/img/dan-stencil-portrait-400x400.png'

# Custom vars
version:          1.2.0
github:
  repo:           https://github.com/hyperparticle/hyperparticle.github.io

# Gems
plugins: [jekyll-paginate]
